(part "SMACONNECTOR18MM"
    (packageRef "SMACONNECTOR18MM")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "471-SMACONNECTOR18MM")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/LPRS/SMACONNECTOR18MM?qs=Z%252BL2brAPG1Jyi4uHcEJFJw%3D%3D")
    (property "Manufacturer_Name" "LPRS")
    (property "Manufacturer_Part_Number" "SMACONNECTOR18MM")
    (property "Description" "RF Connectors / Coaxial Connectors Right Angled SMA Connector with extended 18mm neck")
    (property "Datasheet_Link" "")
    (property "symbolName1" "SMACONNECTOR18MM")
)
