(part "RLS-397"
    (packageRef "RLS397")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "919-RLS-397")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/RECOM-Power/RLS-397?qs=gZXFycFWdAMzj7SWZ0VCrw%3D%3D")
    (property "Manufacturer_Name" "RECOM Power")
    (property "Manufacturer_Part_Number" "RLS-397")
    (property "Description" "Inductor Power Unshielded Wirewound 3.9uH 20% 100KHz 1.32A 0.14Ohm DCR 1812 Bag")
    (property "Datasheet_Link" "https://recom-power.com/pdf/Accessories/RLS-397.pdf")
    (property "symbolName1" "RLS-397")
)
