(part "R-781_8-0_5"
    (packageRef "R781805")
    (interface
        (port "1" (symbPinId 1) (portName "+VIN") (portType INOUT))
        (port "2" (symbPinId 2) (portName "GND") (portType INOUT))
        (port "3" (symbPinId 3) (portName "+VOUT") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "919-R-781.8-0.5")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/RECOM-Power/R-7818-05?qs=YWgezujkI1JrqyUZzqm94A%3D%3D")
    (property "Manufacturer_Name" "RECOM Power")
    (property "Manufacturer_Part_Number" "R-781.8-0.5")
    (property "Description" "Recom Through Hole Switching Regulator, 1.8V dc Output Voltage, 4.75  32V dc Input Voltage, 500mA Output Current")
    (property "Datasheet_Link" "https://recom-power.com/pdf/Innoline/R-78-0.5.pdf")
    (property "symbolName1" "R-781_8-0_5")
)
